name: my_app2
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_mjpeg: ^2.0.4
  http: ^0.13.6
  image_picker: ^1.0.4
  flutter_image_compress: ^2.0.4
  video_player: ^2.8.3
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  camera: ^0.10.5+7
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


